### ISSUE TITLE
Not compatible with unplugin-markdown-it

### ISSUE THREAD

**Issue by vazir** [Bioruebe/markdown-it-collapsible#3]
node_modules/markdown-it-collapsible/dist/index.js:1
import Token from "markdown-it/lib/token";
^^^^^^

SyntaxError: Cannot use import statement outside a module

**Comment by Bioruebe** [comment]
I just released version 2.0.1, which should fix the import problem. Please check if that works for you.

**Comment by egeesin** [comment]
In 2.0.0, I was having same error although I had the conditions unrelated to the title. Plugin works fine for me in the latest version.
